version: '3'
services:
  nodejs:
    container_name: node
    image: ${{ secrets.DOCKER_USER }}/ga:latest
    ports:
      - 3000:3000
    restart: always
    networks:
      - net-phpmsql
    depends_on:
      - mysqlc
networks:
  net-phpmsql: